title: Clinton Pracher: Operator Portfolio
description: Product leader who builds decision systems.
baseurl: "/operator-portfolio"
url: "https://clintonpracher.github.io"
theme: minima
markdown: kramdown
